"""create tables

Revision ID: d3c8f8bd31a1
Revises: 
Create Date: 2023-05-07 20:36:03.611749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c8f8bd31a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resort',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_region', sa.String(), nullable=False),
    sa.Column('location_state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('location_region', sa.String(), nullable=False),
    sa.Column('location_state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('resort_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resort_id'], ['resort.id'], name=op.f('fk_pass_resort_id_resort')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pass_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pass_id'], ['pass.id'], name=op.f('fk_recommendation_pass_id_pass')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_recommendation_user_id_user')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation')
    op.drop_table('pass')
    op.drop_table('user')
    op.drop_table('resort')
    # ### end Alembic commands ###
